// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGff9eZ0RquXzfWErRVqMObPHyghMsVfo',
    appId: '1:269709383838:web:52797f8b7c9f9a8da4838f',
    messagingSenderId: '269709383838',
    projectId: 'voleyballapp-c7b9f',
    authDomain: 'voleyballapp-c7b9f.firebaseapp.com',
    databaseURL: 'https://voleyballapp-c7b9f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'voleyballapp-c7b9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZZSJYxVyJUMGgBmKreD3xtQZVDt_EvrM',
    appId: '1:269709383838:android:3c8e5ef1b8c99149a4838f',
    messagingSenderId: '269709383838',
    projectId: 'voleyballapp-c7b9f',
    databaseURL: 'https://voleyballapp-c7b9f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'voleyballapp-c7b9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJrybIv3K7QUI9yKIVCQiGQ8kSMqYvUTA',
    appId: '1:269709383838:ios:31e367d91ba1d52fa4838f',
    messagingSenderId: '269709383838',
    projectId: 'voleyballapp-c7b9f',
    databaseURL: 'https://voleyballapp-c7b9f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'voleyballapp-c7b9f.firebasestorage.app',
    androidClientId: '269709383838-8av5j0d7ejuc5vu172c1brslj4skte6c.apps.googleusercontent.com',
    iosClientId: '269709383838-1gigvmsvg0u9fdkleb9p0s7864fi6id6.apps.googleusercontent.com',
    iosBundleId: 'com.example.volleyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJrybIv3K7QUI9yKIVCQiGQ8kSMqYvUTA',
    appId: '1:269709383838:ios:31e367d91ba1d52fa4838f',
    messagingSenderId: '269709383838',
    projectId: 'voleyballapp-c7b9f',
    databaseURL: 'https://voleyballapp-c7b9f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'voleyballapp-c7b9f.firebasestorage.app',
    androidClientId: '269709383838-8av5j0d7ejuc5vu172c1brslj4skte6c.apps.googleusercontent.com',
    iosClientId: '269709383838-1gigvmsvg0u9fdkleb9p0s7864fi6id6.apps.googleusercontent.com',
    iosBundleId: 'com.example.volleyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGff9eZ0RquXzfWErRVqMObPHyghMsVfo',
    appId: '1:269709383838:web:852e7304603c70d8a4838f',
    messagingSenderId: '269709383838',
    projectId: 'voleyballapp-c7b9f',
    authDomain: 'voleyballapp-c7b9f.firebaseapp.com',
    databaseURL: 'https://voleyballapp-c7b9f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'voleyballapp-c7b9f.firebasestorage.app',
  );

}