// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrFuIiGkijy4vPogBM2mcZBQAL1826dQ4',
    appId: '1:293074804322:web:9d937f04b503039667fb3b',
    messagingSenderId: '293074804322',
    projectId: 'volleyapp-fdd77',
    authDomain: 'volleyapp-fdd77.firebaseapp.com',
    storageBucket: 'volleyapp-fdd77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdE75xQ4yYCCXGtrfYts_Jmcjq4wSmkZs',
    appId: '1:293074804322:android:b54fbf5eb6b0bd1867fb3b',
    messagingSenderId: '293074804322',
    projectId: 'volleyapp-fdd77',
    storageBucket: 'volleyapp-fdd77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK3qLvD5zwU8SSFGR_W9D28YvvexiSQEI',
    appId: '1:293074804322:ios:1bd96da1719b6aed67fb3b',
    messagingSenderId: '293074804322',
    projectId: 'volleyapp-fdd77',
    storageBucket: 'volleyapp-fdd77.firebasestorage.app',
    iosBundleId: 'com.example.volleyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK3qLvD5zwU8SSFGR_W9D28YvvexiSQEI',
    appId: '1:293074804322:ios:1bd96da1719b6aed67fb3b',
    messagingSenderId: '293074804322',
    projectId: 'volleyapp-fdd77',
    storageBucket: 'volleyapp-fdd77.firebasestorage.app',
    iosBundleId: 'com.example.volleyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrFuIiGkijy4vPogBM2mcZBQAL1826dQ4',
    appId: '1:293074804322:web:601f480697b12c5467fb3b',
    messagingSenderId: '293074804322',
    projectId: 'volleyapp-fdd77',
    authDomain: 'volleyapp-fdd77.firebaseapp.com',
    storageBucket: 'volleyapp-fdd77.firebasestorage.app',
  );
}
